all: install run

install:
	pipenv install --skip-lock

run:
	pipenv run python default.py

shell:
	pipenv shell

pshell:
	pipenv run ipython

clean:
	pipenv --rm

# vim: tabstop=3 noexpandtab shiftwidth=3 softtabstop=3
